apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop
  name: sa-reader
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: roboshop
  name: sa-reader
subjects:
- kind: ServiceAccount
  name: roboshop-password # name of the service account
  namespace: roboshop
roleRef:
  kind: Role
  name: sa-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1  
kind: Pod
metadata:
  name: aws-cli
  namespace: roboshop
  labels:
    purpose: sa 
spec:
  serviceAccount: password
  containers:
  - name: awscli
    image: amazon/aws-cli
    command: ["sleep","10000"]